/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoszykRouteImport } from './routes/koszyk'
import { Route as SklepRouteImport } from './routes/sklep'
import { Route as ProduktSlugRouteImport } from './routes/produkt.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoszykRoute = KoszykRouteImport.update({
  id: '/koszyk',
  path: '/koszyk',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepRoute = SklepRouteImport.update({
  id: '/sklep',
  path: '/sklep',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktSlugRoute = ProduktSlugRouteImport.update({
  id: '/produkt/$slug',
  path: '/produkt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/koszyk': typeof KoszykRoute
  '/sklep': typeof SklepRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/koszyk': typeof KoszykRoute
  '/sklep': typeof SklepRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/koszyk': typeof KoszykRoute
  '/sklep': typeof SklepRoute
  '/produkt/$slug': typeof ProduktSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/koszyk' | '/sklep' | '/produkt/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/koszyk' | '/sklep' | '/produkt/$slug'
  id: '__root__' | '/' | '/koszyk' | '/sklep' | '/produkt/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KoszykRoute: typeof KoszykRoute
  SklepRoute: typeof SklepRoute
  ProduktSlugRoute: typeof ProduktSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koszyk': {
      id: '/koszyk'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof KoszykRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep': {
      id: '/sklep'
      path: '/sklep'
      fullPath: '/sklep'
      preLoaderRoute: typeof SklepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$slug': {
      id: '/produkt/$slug'
      path: '/produkt/$slug'
      fullPath: '/produkt/$slug'
      preLoaderRoute: typeof ProduktSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KoszykRoute: KoszykRoute,
  SklepRoute: SklepRoute,
  ProduktSlugRoute: ProduktSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
